-- 将该建表 SQL 语句，添加到 yudao-module-hq-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hq_customer" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "customer_name" varchar,
    "telphone" varchar,
    "sale_id" bigint,
    "sex" varchar,
    "order_money" int,
    "unit" varchar,
    "login_ip" varchar,
    "login_date" datetime,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint,
    "status" int NOT NULL,
    "email" varchar,
    "allocation_status" varchar,
    "boss_id" bigint,
    "order_id" bigint,
    PRIMARY KEY ("id")
) COMMENT 'hq用户表';

-- 将该删表 SQL 语句，添加到 yudao-module-hq-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "hq_customer";
